### ISSUE TITLE
不操作bitmap有啥优势？

### ISSUE THREAD

**Issue by wowo3129** [FlyJingFish/ShapeImageView#1]
是不是意味着同样的圆角效果，不操作bitmap的话，内存会少占用？我查看了网上基本上都是对bitmap进行了裁剪，这样是不是意味着内存会多出来一份bitmap占用，我的qq想沟通下 1094035520

**Comment by FlyJingFish** [comment]
Drawable比Bitmap内存占用少，可以了解下，试想下Glide为啥默认加载出来的是Drawable而不是Bitmap

**Comment by wowo3129** [comment]
我用glide设置565格式加载在线jpg图片，发现内存中的bitmap被自动转为8888格式加载了，不知道楼主遇到过没，有啥好的方案？

**Comment by FlyJingFish** [comment]
你是指Glide加载出来的bitmap变成8888了？还是本库的ImageView？
