### ISSUE TITLE
如果要用这个绘制一个矩形图片，对他描边，并且带圆角，要怎么设置？

### ISSUE THREAD

**Issue by wowo3129** [FlyJingFish/ShapeImageView#2]

**Comment by wowo3129** [comment]
找到了你的csdn，里面看可以配置

**Comment by FlyJingFish** [comment]
看demo里有使用矩形边框，只需要把padding值设置的和边框宽度一样就可以有描边的效果

**Comment by FlyJingFish** [comment]
如果想给边框和图像有个距离把padding值设置的比边框线宽大就可以了。从你设计图来设置就好了。另外使用说明首页有了，可以看中文使用文档
