### ISSUE TITLE
AlmightyShapeImageView用png锯齿还是比较明显，使用shape或者是vector会不会有适配问题

### ISSUE THREAD

**Issue by ender115** [FlyJingFish/ShapeImageView#4]
AlmightyShapeImageView会用png锯齿还是比较明显，使用shape或者是vector会不会有适配问题

**Comment by FlyJingFish** [comment]
shape或vector不但不会有适配问题，相反的效果会更好。不建议用png格式图，强烈建议使用vector，你可以看页面上我给出的说明链接自行转化一下，可以让ui出svg格式图直接可以用Android studio转化为Vector。
