### ISSUE TITLE
AlmightyShapeImageView卡顿

### ISSUE THREAD

**Issue by ender115** [FlyJingFish/ShapeImageView#5]
AlmightyShapeImageView用vector在RecyclerView列表里面使用的话在部分手机上比较卡，第一次加载时间比较久，滑动的时候也会卡，大佬有碰到这个问题么

**Comment by FlyJingFish** [comment]
vector的代码，你截个图给我看下

**Comment by FlyJingFish** [comment]
库内内置 ic_vector_star，你把你的vector换成这个测试一下还卡顿吗

**Comment by ender115** [comment]
是我们item上面设置了特殊字体导致的卡顿，AlmightyShapeImageView设置边框的话用什么方式比较好，我用一张背景图放到底部，然后上面放AlmightyShapeImageView设置padding，效果是可以达到，但是感觉有些复杂一点的图形边框没那么均匀，有的地方宽，有的地方窄

**Comment by FlyJingFish** [comment]
1、我还纳闷呢，我之前做完测过绘制速度，都测不出来绘制的时间，多数时候都是0毫秒，极少数1毫秒即可绘制完毕……使用的代码都是不会存在兼容性的，所以可放心使用
2、至于边框的设置， `AlmightyShapeImageView` 使用起来其实和 `系统的 ImageView` 没有任何区别的，你的边框显示有问题，应该是您自身的问题，你的边框是否使用的是png图片呢，如果是的话很容易出现问题，建议使用shape。如果还有疑问可把你的代码和实际显示效果截图上来讨论

**Comment by FlyJingFish** [comment]
如果是复杂图形边框套复杂图形，需要按照设置padding后图片的大小和显示边框的大小的宽高比来让UI切图。简单来说就是UI切的边框图和图形在不缩放的情况下，摆在一起看起来没问题才行。这样缩放是才不至于出现问题。例如边框图是100×100假如四个边的padding分别都是6，那图形就得是88×88，并且切好的图摆在一起看着没问题了你设置上去就问题不大
